// <auto-generated />
using BreakFast.Catalog.API.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakFast.Catalog.API.Infrastructures.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20240519164528_Initial_migration")]
    partial class Initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BreakFast.Catalog.API.Domain.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ukrainian Traditional meal",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Borch with cream",
                            Price = 85.549999999999997,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Original recipe",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Vareniki",
                            Price = 150.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Original recipe from Japan",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sushi with avocado",
                            Price = 190.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Weight of set 500g.",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sushi California",
                            Price = 230.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Very hot and unforgettable",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Soup with Red Hot Chili Pepper",
                            Price = 350.0,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Very popular meal from Thailand",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Noodles with seafood",
                            Price = 299.99000000000001,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("BreakFast.Catalog.API.Domain.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Restaurant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "st. Second 1, Kiev",
                            Email = "ukrainiancuisine@gamil.com",
                            IsDeleted = false,
                            Name = "Ukrainian Cuisine",
                            PhoneNumber = "+380773698741",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "st. Main 198, Kiev",
                            Email = "sushistar@gamil.com",
                            IsDeleted = false,
                            Name = "Sushi Star",
                            PhoneNumber = "+380778899445",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "st. Narrow 33, Kiev",
                            Email = "hitai@gamil.com",
                            IsDeleted = false,
                            Name = "HiTai",
                            PhoneNumber = "+380777412369",
                            Status = 0
                        });
                });

            modelBuilder.Entity("BreakFast.Catalog.API.Domain.Models.MenuItem", b =>
                {
                    b.HasOne("BreakFast.Catalog.API.Domain.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("BreakFast.Catalog.API.Domain.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
